### ISSUE TITLE
Cryptic Python create failure at AddressProof step

### ISSUE THREAD

**Issue by Sjors** [rustyrussell/bolt12address#1]
Using the following (with NODE_ID replaced with my node id):

```
./bolt12address.py create me@example.com /.../privkey.pem /.../cert.pem /.../chain.pem NODE_ID  --description "Open source development donation" --chain bitcoin
```

The following cryptic error is thrown:
```
Traceback (most recent call last):
  File "/home/sjimmie/src/bolt12address/python/./bolt12address.py", line 262, in <module>
    args.func(args)
  File "/home/sjimmie/src/bolt12address/python/./bolt12address.py", line 168, in create
    ap = AddressProof.create(args.vendor,
  File "/home/sjimmie/src/bolt12address/python/./bolt12address.py", line 31, in create
    self = cls(None)
  File "/home/sjimmie/src/bolt12address/python/./bolt12address.py", line 19, in __init__
    super().__init__("lnap", generated.tlv_addressproof, proof)
  File "/home/sjimmie/.pyenv/versions/3.9.6/lib/python3.9/site-packages/bolt12/bolt12.py", line 289, in __init__
    self.values, self.unknowns = helper_fromwire_tlv(tlv_table, bytestr)
  File "/home/sjimmie/.pyenv/versions/3.9.6/lib/python3.9/site-packages/bolt12/bolt12.py", line 37, in helper_fromwire_tlv
    while len(buffer) != 0:
TypeError: object of type 'NoneType' has no len()
```

I guess it's missing something, but it's not clear what.

**Comment by rustyrussell** [comment]
Oops!  I forgot to push my bolt12 changes!

**Comment by Sjors** [comment]
I pulled the latest master and reinstalled the requirements.txt. Now the command ran without error.

https://sprovoost.nl/.well-known/bolt12/bitcoin/sjors@sprovoost.nl

The check command fails though, but I'll make a new issue for that.
