### ISSUE TITLE
Python check fails

### ISSUE THREAD

**Issue by Sjors** [rustyrussell/bolt12address#6]
I created a thing using the Python incantation in #1 (master branch commit c4c55b74bee63d840605c3656cc83fdc9984b77d)

https://sprovoost.nl/.well-known/bolt12/bitcoin/sjors@sprovoost.nl

But the verification fails:

```
./bolt12address.py check --raw-stdin < /var/www/well-known/bolt12/bitcoin/sjors@sprovoost.nl 
Traceback (most recent call last):
  File "/home/sjimmie/src/bolt12address/python/./bolt12address.py", line 339, in <module>
    args.func(args)
  File "/home/sjimmie/src/bolt12address/python/./bolt12address.py", line 189, in check
    ap = AddressProof(sys.stdin.buffer.read())
  File "/home/sjimmie/src/bolt12address/python/./bolt12address.py", line 21, in __init__
    super().__init__("lnap", generated.tlv_addressproof, proof)
  File "/home/sjimmie/.pyenv/versions/3.9.6/lib/python3.9/site-packages/bolt12/bolt12.py", line 293, in __init__
    self.values, self.unknowns = helper_fromwire_tlv(tlv_table, bytestr)
  File "/home/sjimmie/.pyenv/versions/3.9.6/lib/python3.9/site-packages/bolt12/bolt12.py", line 56, in helper_fromwire_tlv
    raise ValueError('Invalid: Unknown even field number {}'.format(tlv_type))
ValueError: Invalid: Unknown even field number 108
```

`lightning-cli decode` thinks the whole string Is broken: `string: Bad bech32 string: invalid token '\"lnap1...5kj6zs\"'"`

**Comment by rustyrussell** [comment]
You are supposed to generate with --raw?  I know, it's weird, the default is to make it human readable, perhaps I should change that....

**Comment by Sjors** [comment]
I have no idea what I'm doing, so having good defaults is probably a good idea...

But yes, regenerating with `--raw` helped: it now sees the `offer_id` too.
